import { MAX_NUMBER_DECIMALS } from '@app/common/constants'

export const BALANCE_CONNECTION = 'BALANCE_CONNECTION'
export const DEFAULT_LIMIT = 10
export const ACCOUNT_LIST_MAX_ITEMS = 100
export const MAX_BALANCE_HISTORIES = 100
export const MAX_BALANCE_SNAPSHOTS = 500
export const MIN_TIMEZONE = -12
export const MAX_TIMEZONE = 14
export const MIN_RESOLUTION = 60000
export const TRANSACTION_REFERENCE_ID_MAX_LENGTH = 64
export const HOLD_TRANSACTION_REFERENCE_ID_MAX_LENGTH = 64
export const CURRENCY_MAX_LENGTH = 36
export const VALIDATION_LOCALE = 'en-US'

export enum BALANCE_TYPE {
  UNKNOWN = 0,
  CASHBACK = 1,
  BO = 2,
  EXCHANGE = 3,
  REWARD = 4,
  FUTURES = 5,
}

export enum TRANSACTION_TYPE {
  UNKNOWN = 0,
  TRADING_FEE = 1,
  WITHDRAW = 2,
  WITHDRAW_FEE = 3,
  DEPOSIT = 4,
  DEPOSIT_FEE = 5,
  TRANSFE = 6,
  TRANSFER_FEE = 7,
  AFFILIATE = 8,
  MANUALLY = 9,
  BO_TRADING = 10,
  BO_TRADING_FEE = 11,
  REWARD = 12,
  BO_TRANSFER = 13,
  BO_TRANSFER_FEE = 14,
  DIVIDEND = 15,
  COMMISSION = 16,
  CAMPAIGN = 17,
  TRADING = 18,
  SWAP = 19,
  CORRECT = 20,
  DIVIDEND_ROLLBACK = 21,
  BO_TRADING_ODD = 22,
  BO_TRADING_ODD_WIN = 23,
  TRADING_FEE_ROLLBACK = 24,
  IMPORT_EXCEL = 25,
  IMPORT_EXCEL_ROLLBACK = 26,
}

export enum ON_HOLD_TRANSACTION_STATUS {
  NEW = 0,
  PARTIAL_FILLED = 1,
  COMPLETED = 2,
  CANCELLED = 3,
}

export enum ABNORMAL_BALANCE_ACCOUNT_STATUS {
  NEW = 0,
  REJECTED = 1,
  COMPLETED = 2,
}

export enum ACTION_CORRECT_TYPE {
  CORRECT = 1,
  REJECT = 2,
}

export enum CORRECTED_TYPE {
  CORRECT_BALANCE_ACCOUNT_TO_TRANSACTION = 1,
  CORRECT_BALANCE_TRANSACTION_TO_ACCOUNT = 2,
}

export enum RUN_CHECK_BALANCE_TYPE {
  RUN_ALL = 1,
  RUN_NEXT_HISTORY = 2,
}

export const VALIDATION_ERRORS = {
  BALANCE_TYPE_IS_ENUM: 'BALANCE_TYPE_IS_ENUM',
  BALANCE_TYPE_IS_INVALID: 'BALANCE_TYPE_IS_INVALID',
  TRANSACTION_TYPE_IS_ENUM: 'TRANSACTION_TYPE_IS_ENUM',
  CURRENCY_IS_ALPHANUMERIC: 'CURRENCY_IS_ALPHANUMERIC',
  CURRENCY_MAX_LENGTH: 'CURRENCY_MAX_LENGTH_$constraint1',
  AMOUNT_IS_DECIMAL: 'AMOUNT_IS_DECIMAL_' + MAX_NUMBER_DECIMALS,
  AMOUNT_FIXED_NUMBER_IS_NOT_ZERO: 'AMOUNT_FIXED_NUMBER_IS_NOT_ZERO',
  AMOUNT_FIXED_NUMBER_IS_NEGATIVE: 'AMOUNT_FIXED_NUMBER_IS_NEGATIVE',
  AMOUNT_FIXED_NUMBER_IS_POSITIVE: 'AMOUNT_FIXED_NUMBER_IS_POSITIVE',
  USER_ID_IS_NUMBER: 'USER_ID_IS_NUMBER',
  IS_NUMBER_STRING: 'IS_NUMBER_STRING',
  TRANSACTION_REFERENCE_ID_REQUIRED: 'TRANSACTION_REFERENCE_ID_REQUIRED',
  TRANSACTION_REFERENCE_ID_MAX_LENGTH:
    'TRANSACTION_REFERENCE_ID_MAX_LENGTH_$constraint1',
  HOLD_REFERENCE_ID_REQUIRED: 'HOLD_REFERENCE_ID_REQUIRED',
  HOLD_REFERENCE_ID_MAX_LENGTH: 'HOLD_REFERENCE_ID_MAX_LENGTH_$constraint1',
  HOLD_REFERENCE_ID_SAME_VALUE: 'HOLD_REFERENCE_ID_SAME_VALUE',
  REQUESTS_ARRAY_MIN_SIZE: 'REQUESTS_ARRAY_MIN_SIZE_$constraint1',
  ITEMS_ARRAY_MIN_SIZE: 'ITEMS_ARRAY_MIN_SIZE_$constraint1',
  HOLD_BALANCE_ITEMS_REQUIRED: 'HOLD_BALANCE_ITEMS_REQUIRED',
  CHANGE_BALANCE_ITEMS_REQUIRED: 'CHANGE_BALANCE_ITEMS_REQUIRED',
  AUTO_CONFIRM_IS_IN: 'AUTO_CONFIRM_IS_IN_$constraint1',
  AUTO_CONFIRM_IS_ACCEPTED: 'AUTO_CONFIRM_IS_ACCEPTED',
  PAGINATION_LIMIT_IS_INT: 'PAGINATION_LIMIT_IS_INT',
  PAGINATION_LIMIT_MIN: 'PAGINATION_LIMIT_MIN_$constraint1',
  PAGINATION_LIMIT_MAX: 'PAGINATION_LIMIT_MAX_$constraint1',
  PAGINATION_FROM_ID_IS_NUMBER_STRING: 'PAGINATION_FROM_ID_IS_NUMBER_STRING',
  PAGINATION_TO_ID_IS_NUMBER_STRING: 'PAGINATION_TO_ID_IS_NUMBER_STRING',
  FROM_TIME_IS_NUMBER: 'FROM_TIME_IS_NUMBER',
  TO_TIME_IS_NUMBER: 'TO_TIME_IS_NUMBER',
  RESOLUTION_IS_NUMBER: 'RESOLUTION_IS_NUMBER',
  TIMEZONE_IS_NUMBER: 'TIMEZONE_IS_NUMBER',
  TIMEZONE_MIN: 'TIMEZONE_MIN',
  TIMEZONE_MAX: 'TIMEZONE_MAX',
  ABNORMAL_BALANCE_ACCOUNT_ID_IS_NUMBER:
    'ABNORMAL_BALANCE_ACCOUNT_ID_IS_NUMBER',
  ACTION_CORRECT_TYPE_IS_ENUM: 'ACTION_CORRECT_TYPE_IS_ENUM',
  CORRECT_TYPE_IS_ENUM: 'CORRECT_TYPE_IS_ENUM',
  CHANGE_ACTUAL_BALANCE_IS_FIXED_NUMBER:
    'CHANGE_ACTUAL_BALANCE_IS_FIXED_NUMBER',
  CHANGE_AVAILABLE_BALANCE_IS_FIXED_NUMBER:
    'CHANGE_AVAILABLE_BALANCE_IS_FIXED_NUMBER',
  ID_IS_NOT_EMPTY: 'ID_IS_NOT_EMPTY',
  ID_IS_NUMBER: 'ID_IS_NUMBER',
  EMAIL_IS_NOT_EMPTY: 'EMAIL_IS_NOT_EMPTY',
  INVALID_EMAIL_ADDRESS: 'INVALID_EMAIL_ADDRESS',
  CURRENCY_IS_NOT_EMPTY: 'CURRENCY_IS_NOT_EMPTY',
  SORT_FIELD_ONLY_SUPPORT: 'SORT_FIELD_ONLY_SUPPORT',
  SEARCH_FIELD_ONLY_SUPPORT: 'SEARCH_FIELD_ONLY_SUPPORT',
}

export const ERRORS = {
  BALANCE_ACCOUNT_NOT_FOUND: {
    code: 10001,
    message: 'BALANCE_ACCOUNT_NOT_FOUND',
  },
  TRANSACTION_EXISTS: {
    code: 10002,
    message: 'TRANSACTION_EXISTS',
  },
  INSUFFICIENT_BALANCE: {
    code: 10005,
    message: 'INSUFFICIENT_BALANCE',
  },
  INSUFFICIENT_AVAILABLE_BALANCE: {
    code: 10006,
    message: 'INSUFFICIENT_AVAILABLE_BALANCE',
  },
  CANNOT_CONFIRM: {
    code: 10007,
    message: 'CANNOT_CONFIRM',
  },
  CANNOT_CANCEL: {
    code: 10008,
    message: 'CANNOT_CANCEL',
  },
  DUPLICATE_HOLD_REFERENCE_ID: {
    code: 10009,
    message: 'DUPLICATE_HOLD_REFERENCE_ID',
  },
  DUPLICATE_TRANSACTION_REFERENCE_ID: {
    code: 10010,
    message: 'DUPLICATE_TRANSACTION_REFERENCE_ID',
  },
  CANNOT_GET_COIN_PRICE: {
    code: 10011,
    message: 'CANNOT_GET_COIN_PRICE',
  },
  BALANCE_ACCOUNT_NOT_ENOUGH_AMOUNT: {
    code: 10012,
    message: 'BALANCE_ACCOUNT_NOT_ENOUGH_AMOUNT',
  },
  BALANCE_ACCOUNT_SAME_TYPE_FOR_TRANSFER: {
    code: 10013,
    message: 'BALANCE_ACCOUNT_SAME_TYPE_FOR_TRANSFER',
  },
  CANNOT_GET_COIN_LIST: {
    code: 10014,
    message: 'CANNOT_GET_COIN_LIST',
  },
}
export enum SORT_TYPE {
  ASC = 'ASC',
  DESC = 'DESC',
}

export enum SETTING_CONVERT_STATUS {
  ENABLE = 1,
  DISABLE = 2,
}

export enum SETTING_CONVERT_FEE_TYPE {
  AMOUNT = 1,
  RATIO = 2,
}

export enum BALANCE_CONVERT_STATUS {
  NEW = 1,
  COMPLETED = 2,
  REJECTED = 3,
}
