export enum EValidationError {
  FAIL = 'VALIDATION.FAIL',
  REQUIRED = 'VALIDATION.REQUIRED',
  IS_EMAIL = 'VALIDATION.IS_EMAIL',
  IS_NUMBER = 'VALIDATION.IS_NUMBER',
  IS_STRING = 'VALIDATION.IS_STRING',
  IS_DATE = 'VALIDATION.IS_DATE',
  MIN_LENGTH = 'VALIDATION.MIN_LENGTH_$constraint1',
  MAX_LENGTH = 'VALIDATION.MAX_LENGTH_$constraint1',
  MATCHES = 'VALIDATION.MATCHES',
  PASSWORD_TOO_WEAK = 'VALIDATION.PASSWORD_TOO_WEAK',
  IS_ENUM = 'VALIDATION.IS_ENUM',
  IS_FILE_TYPE = 'VALIDATION.IS_FILE_TYPE',
  IS_FILE_EXTENSION = 'VALIDATION.IS_FILE_EXTENSION',
  MAX_FILE_SIZE = 'VALIDATION.MAX_FILE_SIZE_$constraint1',
  ARRAY_MAX_SIZE = 'VALIDATION.ARRAY_MAX_SIZE_$constraint1',
  MAX_NUMBER = 'VALIDATION.MAX_NUMBER_$constraint1',
  MAX_DATE = 'VALIDATION.MAX_DATE_$constraint1',
}

export const TokenError = {
  INVALID: { code: 42001, message: 'TOKEN.INVALID' },
  EXPIRED: { code: 42002, message: 'TOKEN.EXPIRED' },
}

export const CommonError = {
  NOT_FOUND: { code: 400, message: 'NOT_FOUND' },
}

export const GroupNotificationError = {
  CAN_NOT_CHANGE_AFTER_PUBLISHED: {
    code: 43001,
    message: 'GLOBAL_NOTIFICATION.CAN_NOT_CHANGE_AFTER_PUBLISHED',
  },
}
