export enum STATUS {
  WAITING = 1,
  PROCESSING = 2,
  SUCCESS = 3,
  FAIL = 4,
  NOT_FOUND = 5,
  DUPLICATED_BANNED = 6,
}

export enum STATUS_NOTE {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  DUPLICATED_BANNED = 'DUPLICATED_BANNED',
  ALREADY_BANNED = 'ALREADY_BANNED',
}
