export enum ErrorMessage {
  UNKNOWN = 'UNKNOWN',
  INVALID_CAMPAIGN_TIME = 'CAMPAIGN.UPDATE.INVALID_TIME',
  INVALID_CAMPAIGN_TYPE = 'CAMPAIGN.UPDATE.INVALID_TYPE',
  DUPLICATE_MISSION_PRIORITY = 'MISSION.DUPLICATE_PRIORITY',
  INVALID_MISSION_TIME = 'MISSION.INVALID_TIME',
}
