export enum TRANSACTION_TYPE {
  TRADING_FEE = 1,
  WITHDRAW = 2,
  WITHDRAW_FEE = 3,
  DEPOSIT = 4,
  DEPOSIT_FEE = 5,
  TRANSFER = 6,
  TRANSFER_FEE = 7,
  AFFILIATE = 8,
  MANUALLY = 9,
  BO_TRADING = 10,
  BO_TRADING_WIN = 11,
  REWARD = 12,
  BO_TRANSFER = 13,
  BO_TRANSFER_FEE = 14,
  DIVIDEND = 15,
  COMMISSION = 16,
  CAMPAIGN = 17,
  TRADING = 18,
  SWAP = 19,
  CORRECT = 20,
  DIVIDEND_ROLLBACK = 21,
  BO_TRADING_ODD = 22,
  BO_TRADING_ODD_WIN = 23,
  TRADING_FEE_ROLLBACK = 24,
  IMPORT_EXCEL = 25,
  IMPORT_EXCEL_ROLLBACK = 26,
}

export enum BALANCE_TYPE {
  CASHBACK = 1,
  BO = 2,
  EXCHANGE = 3,
  REWARD = 4,
  FUTURES = 5,
}

export enum CORRECTED_TYPE {
  CORRECT_BALANCE_ACCOUNT_TO_TRANSACTION = 1,
  CORRECT_BALANCE_TRANSACTION_TO_ACCOUNT = 2,
}
