export enum USER_TAG_MESSAGE {
  ADD_FAIL = 'USER_TAG.ADD_FAIL',
  NOT_FOUND = 'USER_TAG.NOT_FOUND',
  EXISTS = 'USER_TAG.EXISTS',
  UPDATE_FAIL = 'USER_TAG.UPDATE_FAIL',
  DELETE_SUCCESS = 'USER_TAG.DELETE_SUCCESS',
  DELETE_FAIL = 'USER_TAG.DELETE_FAIL',
}
