export * from './rekognition-info.entity'
export * from './rekognition-related-face.entity'
export * from './rekognition-response.entity'
export * from './rekognition-info-history.entity'
export * from './rekognition-index.entity'
