export enum TAG_MESSAGE {
  ADD_FAIL = 'TAG.ADD_FAIL',
  NOT_FOUND = 'TAG.NOT_FOUND',
  EXISTS = 'TAG.EXISTS',
  UPDATE_FAIL = 'TAG.UPDATE_FAIL',
  DELETE_SUCCESS = 'TAG.DELETE_SUCCESS',
  DELETE_FAIL = 'TAG.DELETE_FAIL',
}
