export const TRACE_CODES = {
  m001: '{{name}} not found',
  m002: 'Event registered. Developer please add this event to enum EVENTS',
  m003: 'Event has no corresponding mission',
  m004: '{{name}} was not found or inactive!',
  m005: '{{name}} was over time!',
  m006: '{{condition_name}} Condition check fail!',
  m007: 'Mission reward rules was not exist!',
  m008: 'User has received enough rewards',
  m009: 'Mission had out of budget',
  m010: 'Mission reward was not enough money. Source: {{source}}',
  m011: 'DANGER!!! Update release value fail.',
  m012: 'Compare {{name}} condition fail',
  m013: 'Update reward history fail',
  m014: 'Send reward to {{type}} fail',
  m015: 'Result send {{type}}',
  m016: 'Invalid data struct',
  m017: 'Failed to reach success_count',
  m018: 'Result send failed {{type}}',
  m019: '{{condition_name}} Display condition check fail!',
  m020: 'Flood detected! ',
  m021: 'Error when calculating amount to grant as percentage',
}
