export enum HttpStatus {
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,
  EARLYHINTS = 103,
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  AMBIGUOUS = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  PAYLOAD_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  REQUESTED_RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  I_AM_A_TEAPOT = 418,
  MISDIRECTED = 421,
  UNPROCESSABLE_ENTITY = 422,
  FAILED_DEPENDENCY = 424,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
}

export enum SubErrorCode {
  PERMISSION_DENIED = 403,
  VALIDATION_FAIL = 400,
}

export enum AuthMiddlewareConst {
  AUTH = 'auth',
  UNAUTH = 'unauth',
  GUEST = 'guest',
}

export enum Screen {
  ROLE_LIST = 1,
  ROLE_CREATE = 2,
  ROLE_UPDATE = 3,
  USER_BASIC_INFO = 4,
  USER_LIST_ACCOUNT_LV = 5,
  USER_DETAIL = 6,
  USER_KYC_NEED_TO_APPROVE = 7,
  USER_KYC_REVIEW_OCR = 8,
  CAMPAIGN_LIST = 9,
  USER_KYC_REVIEW_RISK = 10,
  CAMPAIGN_DETAIL = 11,
  USER_TAG_LIST = 12,
  CHANNEL_LIST = 13,
  SETTING_TRADING = 14,
  SETTING_COIN = 15,
  SETTING_COIN_CATEGORY = 16,
  APP_VERSION_SETTING = 17,
  OBM_SETTING_GENERAL = 18,
  OBM_SETTING_SYS_TARGET = 19,
  OBM_SETTING_BALANCE = 20,
  OBM_SETTING_THRESHOLD = 21,
  HISTORY_LOGIN = 22,
  ADMIN_LIST = 23,
  ADMIN_PERMISSION = 24,
  MISSING_REWARDS_LIST = 25,
  WALLET_MOTHER_WALLET_INCIDENT_COLLECTION = 26,
  WALLET_DEPOSIT_INCIDENT_COLLECTION = 27,
  WALLET_MOTHER_WALLET_LIST = 28,
  WALLET_WITHDRAW_WALLET_LIST = 29,
  WALLET_DEPOSIT_WALLET_LIST = 30,
  WALLET_MOTHER_WALLET_SETTING = 31,
  WALLET_BLACKLIST = 32,
  WALLET_WITHDRAW_SETTING = 33,
  WALLET_DEPOSIT_SETTING = 34,
  AUTO_WITHDRAW_GROUP = 35,
  HIGH_LOW_HISORY = 36,
  HIGH_LOW_USER_BALANCE = 37,
  HIGH_LOW_STATISTIC = 38,
  HIGH_LOW_SUSPENSION = 39,
  HIGH_LOW_UNLIMITED_USER = 40,
  HIGH_LOW_SETTING_TRADING = 41,
  HIGH_LOW_SETTING_TRADING_DETAIL = 42,
  EXCHANGE_OPEN_ORDER = 43,
  USER_IMPORT_BAN = 44,
  HIGH_LOW_WINNING_RATE_ANALYSIS = 45,
  EXCHANGE_ORDER_HISTORY = 45,
  EXCHANGE_TRADING_HISTORY = 46,
  HIGH_LOW_SETTING_CRAWLER = 47,
  HIGH_LOW_USER_TRADING_LIMIT = 48,
  HIGH_LOW_NEWS = 49,
  SYSTEM_PUSH_SETTING = 50,
  HIGH_LOW_STATISTIC_CRAWLER = 51,
  SETTING_UNLIMITED_USER = 52,
  MARKET_MAKER = 53,
  HIGH_LOW_BTC_TRANSFER = 54,
  BALANCE_ABNORMAL_LIST = 55,
  HIGH_LOW_EXPORT = 56,
  HIGH_LOW_LEADERBOARD = 57,

  // currency screen
  CURRENCY_SETTING = 60,
  CURRENCY_DOWN = 61,
  REGISTER_NEW_CURRENCY = 62,
  REGISTER_NEW_EB20 = 63,

  //import excel balance
  IMPORT_EXCEL_BALANCE_LIST = 64,
  IMPORT_EXCEL_BALANCE_DETAIL = 65,
  IMPORT_EXCEL_BALANCE_SETTING = 66,

  //* Withdrawal Control
  WALLET_WITHDRAWAL_CONTROL_USER_NOT_CONFIRMED = 150,
  WALLET_WITHDRAWAL_CONTROL_USER_CANCELED = 151,
  WALLET_WITHDRAWAL_CONTROL_APPROVAL_PENDING = 152,
  WALLET_WITHDRAWAL_CONTROL_APPROVED_TRANSACTIONS = 153,
  WALLET_WITHDRAWAL_CONTROL_REMITTED_TRANSACTIONS = 154,
  WALLET_WITHDRAWAL_CONTROL_REJECTED_TRANSACTIONS = 155,

  LIST_FILE_EXPORT = 156,

  // Wallet trezor
  TREZOR_WALLET = 157,

  // language setting
  TRANSLATE_SETTING_LIST = 10000,
  LANGUAGE_SETTING_LIST = 10001,

  // bot setting
  SETTING_BOT = 67,

  EXCHANGE_USER_BLACKLIST = 68,
  EXCHANGE_USER_ZERO_FEE = 72,

  // api management
  API_MANAGEMENT_LIST = 11000,

  WALLET_BCE_DEPOSIT_HISTORY = 69,
  WALLET_BCE_WITHDRAW_HISTORY = 70,

  GLOBAL_NOTIFICATION_LIST = 71,

  ADMIN_ACTION_LOG = 12001,
  // dividend
  DIVIDEND_LIST = 200,
  DIVIDEND_DETAIL = 201,
  DIVIDEND_EDIT = 202,
  DIVIDEND_CODE_LIST = 203,
  DIVIDEND_HISTORY = 204,
  DIVIDEND_DISABLE_USER = 205,
  OBM_MONITOR = 13001,

  // User balance change history
  USER_BALANCE_CHANGE_HISTORY = 300,

  // Spot grid trading
  SPOT_GRID_TRADING_SETTING = 400,
  SPOT_GRID_TRADING = 401,

  // FUTURE
  FUTURES_OPEN_ORDER = 14000,
  FUTURES_ORDER_HISTORY = 14001,
  FUTURES_USER = 14002,
  FUTURES_OPEN_POSITION = 14003,
  FUTURES_SETTING = 14004,

  // MT5
  MT5_PAYMENT_PAYOUT = 1300,
  MT5_PAYMENT_PAYIN = 1301,

  // Convert setting
  CONVERT_SMALL_BALANCE_SCREEN = 500,

  // Convert setting history
  CONVERT_SMALL_BALANCE_HISTORY_SCREEN = 501,
  SWAP_HISTORY_SCREEN = 502,
  TRANSFER_HISTORY_SCREEN = 503,

  // Reason setting
  USER_REASON_CATEGORY_SCREEN = 504,
  USER_REASON_SCREEN = 505,
}

export enum Permission {
  CAMPAIGN_GET_LIST_KAFKA_EVENTS = 1,
  CAMPAIGN_GET_LIST_GRANT_TARGETS = 2,
  CAMPAIGN_GET_LIST_USER_CONDITIONS = 3,
  CAMPAIGN_GET_LIST = 4,
  CAMPAIGN_CREATE = 5,
  CAMPAIGN_READ = 6,
  CAMPAIGN_UPDATE = 7,
  CAMPAIGN_DELETE = 8,
  CAMPAIGN_GET_DISPLAY_CONDITIONS = 9,

  CHANNEL_GET_LIST = 10,
  CHANNEL_CREATE = 11,
  CHANNEL_READ = 12,
  CHANNEL_UPDATE = 13,
  CHANNEL_DELETE = 14,

  MISSION_CREATE = 15,
  MISSION_READ = 16,
  MISSION_UPDATE = 17,

  REJECT_REASON_GET_LIST = 18,

  SETTING_COUNTRY_CODE_GET_LIST = 19,

  TAG_GET_LIST = 20,
  TAG_CREATE = 21,
  TAG_READ = 22,
  TAG_UPDATE = 23,
  TAG_DELETE = 24,

  USER_GET_LIST = 25,
  USER_READ = 26,
  USER_EXPORT = 27,

  USER_MARKETING_GET_LIST = 28,
  USER_MARKETING_EXPORT = 29,

  USER_INFO_READ = 30,
  USER_INFO_READ_HISTORY = 31,

  USER_KYC_READ = 32,
  USER_KYC_READ_ENTERPRISE_INFO = 33,
  USER_KYC_READ_SCAN_DATA = 34,
  USER_KYC_RENEW_SCAN_DATA = 35,
  USER_KYC_REVIEW = 36,
  USER_KYC_READ_ADMIN_DECISIONS = 37,

  ROLE_GET_LIST = 38,
  ROLE_CREATE = 39,
  ROLE_READ = 40,
  ROLE_UPDATE = 41,
  ROLE_DELETE = 42,

  USER_TAG_CREATE = 43,
  USER_TAG_READ = 44,
  USER_TAG_DELETE = 45,

  REWARD_LOG_GET_LIST = 46,
  REWARD_LOG_COUNT = 47,
  REWARD_LOG_RESOLVE = 48,

  COIN_GET_LIST = 49,
  COIN_SEARCH = 50,

  COIN_SETTINGS_CREATE = 51,
  COIN_SETTINGS_READ = 52,
  COIN_SETTINGS_UPDATE = 53,
  COIN_SETTINGS_DELETE = 54,

  PAIR_SETTINGS_CREATE = 55,
  PAIR_SETTINGS_READ = 56,
  PAIR_SETTINGS_UPDATE = 57,
  PAIR_SETTINGS_DELETE = 58,

  PAIR_CATEGORY_SETTINGS_CREATE = 59,
  PAIR_CATEGORY_SETTINGS_READ = 60,
  PAIR_CATEGORY_SETTINGS_UPDATE = 61,
  PAIR_CATEGORY_SETTINGS_DELETE = 62,

  APP_VERSION_CREATE = 63,
  APP_VERSION_READ = 64,
  APP_VERSION_UPDATE = 65,
  APP_VERSION_DELETE = 66,

  ADMIN_GET_LIST = 67,
  ADMIN_CREATE = 68,
  ADMIN_READ = 69,
  ADMIN_UPDATE = 70,
  ADMIN_SET_PERMISSION = 71,

  USER_LOGIN_HISTORY_READ = 72,

  OBM_SETTING_READ = 73,
  OBM_SETTING_UPDATE = 74,
  OBM_SETTING_DELETE = 75,

  WALLET_SETTING_READ = 76,
  WALLET_SETTING_UPDATE = 77,

  USER_EMAIL_CHANGE_HISTORY_READ = 78,

  TOGGLE_BAN_USER = 79,

  AUTO_WITHDRAW_GROUP_COMMON = 80,
  AUTO_WITHDRAW_GROUP_CREATE_UPDATE = 81,
  AUTO_WITHDRAW_GROUP_DETAIL = 82,
  AUTO_WITHDRAW_GENERATE_KEY = 83,
  AUTO_WITHDRAW_CURRENCY = 84,
  AUTO_WITHDRAW_TRANSACTION = 85,
  AUTO_WITHDRAW_HEALTH = 86,

  EXCHANGE_ORDER_READ = 87,
  EXCHANGE_ORDER_UPDATE = 88,

  IMPORT_BAN_USER = 89,

  SYSTEM_PUSH_SETTING_READ = 90,
  SYSTEM_PUSH_SETTING_UPDATE = 91,

  BALANCE_READ = 92,
  BALANCE_ADD = 93,

  BALANCE_TRANSFER_READ = 94,
  BALANCE_TRANSFER_SELF_TRANSFER = 95,
  EXCHANGE_USER_BLACK_LIST_READ = 96,
  EXCHANGE_USER_BLACK_LIST_UPDATE = 97,

  EXCHANGE_USER_UNLIMITED_READ = 98,
  EXCHANGE_USER_UNLIMITED_UPDATE = 99,

  EXCHANGE_USER_ZERO_FEE_READ = 100,
  EXCHANGE_USER_ZERO_FEE_UPDATE = 101,

  MARKET_MAKER_READ = 102,

  BALANCE_ABNORMAL_READ = 103,
  BALANCE_ABNORMAL_UPDATE = 104,

  MARKET_MAKER_MONITOR = 105,

  BALANCE_FILE_IMPORT_READ = 106,
  BALANCE_FILE_IMPORT_CREATE = 107,
  BALANCE_FILE_SETTING_READ = 108,
  BALANCE_FILE_SETTING_CREATE = 111,
  BALANCE_HISTORY = 112,

  // Auto Add
  AUTO_ADD_SETTING_CREATE = 10000,
  AUTO_ADD_SETTING_UPDATE = 10001,
  AUTO_ADD_SMART_CONTRACT_GET = 10002,
  AUTO_ADD_SETTING_LIST = 10003,
  AUTO_ADD_SETTING_READ = 10004,

  MULTI_LANGUAGE_IMPORT_TRANSLATE = 11000,
  MULTI_LANGUAGE_GET_TRANSLATES = 11001,
  MULTI_LANGUAGE_SET_TRANSLATE = 11002,
  MULTI_LANGUAGE_LIST_LANGUAGE = 11003,
  MULTI_LANGUAGE_SET_LANGUAGE = 11004,
  MULTI_LANGUAGE_EXPORT_ALL_TRANSLATE = 11005,

  OBM_BOT_READ = 109,
  OBM_BOT_UPDATE = 110,

  // giangnd added this logic for highlow permission code
  // for prevent duplicate or scale up api, each feature should be increased 10 units and sort by [a-z]
  HIGH_LOW_CRAWL_SETTING_CREATE = 13000,
  HIGH_LOW_CRAWL_SETTING_DELETE = 13001,
  HIGH_LOW_CRAWL_SETTING_READ = 13002,
  HIGH_LOW_CRAWL_SETTING_UPDATE = 13003,
  HIGH_LOW_NEWS_CREATE = 13010,
  HIGH_LOW_NEWS_DELETE = 13011,
  HIGH_LOW_NEWS_READ = 13012,
  HIGH_LOW_NEWS_UPDATE = 13013,
  HIGH_LOW_PAIR_PRICE_CREATE = 13020,
  HIGH_LOW_PAIR_PRICE_DELETE = 13021,
  HIGH_LOW_PAIR_PRICE_READ = 13022,
  HIGH_LOW_PAIR_PRICE_UPDATE = 13023,
  HIGH_LOW_PAIR_SETTING_CREATE = 13030,
  HIGH_LOW_PAIR_SETTING_DELETE = 13031,
  HIGH_LOW_PAIR_SETTING_READ = 13032,
  HIGH_LOW_PAIR_SETTING_UPDATE = 13033,
  HIGH_LOW_SETTING_CREATE = 13040,
  HIGH_LOW_SETTING_DELETE = 13041,
  HIGH_LOW_SETTING_READ = 13042,
  HIGH_LOW_SETTING_UPDATE = 13043,
  HIGH_LOW_TRADING_MODE_CREATE = 13050,
  HIGH_LOW_TRADING_MODE_DELETE = 13051,
  HIGH_LOW_TRADING_MODE_READ = 13052,
  HIGH_LOW_TRADING_MODE_UPDATE = 13053,
  HIGH_LOW_TRADING_PAIR_CREATE = 13060,
  HIGH_LOW_TRADING_PAIR_DELETE = 13061,
  HIGH_LOW_TRADING_PAIR_READ = 13062,
  HIGH_LOW_TRADING_PAIR_UPDATE = 13063,
  HIGH_LOW_UNLIMITED_USER_CREATE = 13070,
  HIGH_LOW_UNLIMITED_USER_DELETE = 13071,
  HIGH_LOW_UNLIMITED_USER_READ = 13072,
  HIGH_LOW_UNLIMITED_USER_UPDATE = 13073,
  HIGH_LOW_USER_BALANCE_READ = 13080,
  HIGH_LOW_USER_TRADING_READ = 13090,
  HIGH_LOW_WINNING_RATE_READ = 13100,
  HIGH_LOW_BLOCK_USER_CREATE = 13110,
  HIGH_LOW_BLOCK_USER_DELETE = 13111,
  HIGH_LOW_BLOCK_USER_READ = 13112,
  HIGH_LOW_USER_GRANT_PAYOUT_CREATE = 13120,
  HIGH_LOW_USER_GRANT_PAYOUT_DELETE = 13121,
  HIGH_LOW_USER_GRANT_PAYOUT_READ = 13122,
  HIGH_LOW_USER_GRANT_PAYOUT_UPDATE = 13123,

  API_MANAGEMENT_LIST = 14000,
  API_MANAGEMENT_DETAIL = 14001,
  API_MANAGEMENT_CHANGE_STATUS = 14002,

  GLOBAL_NOTIFICATION_CREATE = 15001,
  GLOBAL_NOTIFICATION_READ = 15002,
  GLOBAL_NOTIFICATION_UPDATE = 15003,

  NOTIFICATION_CATEGORY_READ = 16001,

  ADMIN_ACTION_LOG_READ = 17001,
  // Dividend
  DIVIDEND_GET_LIST = 200,
  DIVIDEND_GET_DETAIL = 201,
  DIVIDEND_GET_CAMPAIGN_NAME = 202,
  DIVIDEND_GET_CODE_LIST = 203,
  DIVIDEND_GET_ADVANCED = 204,
  DIVIDEND_CREATED = 205,
  DIVIDEND_UPDATE = 206,
  DIVIDEND_CANCEL = 207,
  DIVIDEND_CREATE_CODE = 208,
  DIVIDEND_TOOGLE_CODE = 209,
  DIVIDEND_GET_HISTORY = 210,
  DIVIDEND_GET_LIST_USER_DISABLE = 211,
  DIVIDEND_DISABLE_USER = 212,
  DIVIDEND_DELETE_DISABLE_USER = 213,

  USER_NOTE_CREATE = 18001,
  USER_NOTE_READ = 18002,

  USER_AUTHENTICATOR_RESET = 19001,

  USER_BALANCE_CHANGE_HISTORY = 300,

  USER_CHANGE_EMAIL = 20001,

  GRID_TRADING_SETTING_READ = 30001,
  GRID_TRADING_SETTING_UPDATE = 30002,

  GRID_TRADING_READ = 30003,

  FUTURES_ORDER_READ = 21000,
  FUTURES_ORDER_UPDATE = 21001,
  FUTURES_USER_READ = 21002,
  FUTURES_OPEN_POSITION_READ = 21003,
  FUTURES_SETTINGS_LIST = 21004,

  MT5_PAYMENT_ECHELON_PAYOUT_READ = 22000,
  MT5_PAYMENT_ECHELON_PAYOUT_ADMIN_APPROVE_REQUEST = 22002,
  MT5_PAYMENT_ECHELON_PAYOUT_ADMIN_REJECT_REQUEST = 22003,
  MT5_PAYMENT_ECHELON_PAYIN_READ = 22004,
  MT5_PAYMENT_ECHELON_PAYIN_ADMIN_APPROVE_REQUEST = 22005,
  MT5_PAYMENT_ECHELON_PAYIN_ADMIN_REJECT_REQUEST = 22006,

  USER_INFO_UPDATE = 23000,

  BALANCE_CONVERT_SETTING_GET_LIST = 500,
  BALANCE_CONVERT_SETTING_GET_LOGS = 501,
  BALANCE_CONVERT_SETTING_GET_DETAIL = 502,
  BALANCE_CONVERT_SETTING_CREATE = 503,
  BALANCE_CONVERT_SETTING_UPDATE = 504,
  BALANCE_CONVERT_SETTING_DELETE = 505,
  BALANCE_SWAP_HISTORY = 506,
  BALANCE_TRANSFER_HISTORY = 507,
  BALANCE_CONVERT_SMALL_HISTORY = 508,

  // Reason roles
  USER_REASON_CATEGORY_CREATE = 69696,
  USER_REASON_CATEGORY_UPDATE = 69697,
  USER_REASON_CATEGORY_DELETE = 69698,
  USER_REASON_CATEGORY_GET_LIST = 69699,
  USER_REASON_CREATE = 69700,
  USER_REASON_UPDATE = 69701,
  USER_REASON_DELETE = 69702,
  USER_REASON_GET_LIST = 69703,
}

export enum Feature {
  REVIEW_KYC = 'reviewKyc',
  MANAGE_MARKETING_FUNCTION = 'marketingFunctions',
  MANAGE_ADMIN_ACCOUNT_AND_PERMISSION = 'manageAdminAccountAndPermission',
  MANAGE_WALLET_SETTING = 'manageWalletSetting',
  OBM_SETTING = 'obmSetting',
  EXCHANGE_ORDER = 'exchangeOrder',
  FUTURE = 'future',
  SPOT_GRID = 'spotGrid',
}

export enum OrderbookSide {
  SELL = 2,
  BUY = 1,
}

export enum OrderType {
  LIMIT = 2,
  MARKET = 1,
  STOP_LIMIT = 4,
  STOP_MARKET = 3,
}

export enum ORDER_STATUS {
  PENDING = 1,
  FILLED = 2,
  CANCELED = 3,
  ERROR = 4,
  PARTIAL_FILLED = 5,
  PROCESSING_CANCEL = 6,
  PARTIAL_FILL = 7,
  REJECTED = 9,
}

export enum PAIR_STATUS {
  INACTIVE = 0,
  ACTIVE = 1,
}

export enum SORT_TYPE {
  DESC = -1,
  ASC = 1,
}
