version: '3.9'

services:
  app:
    container_name: admin_fe_dev
    image: admin-fe-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    command: npm run dev
    volumes:
      - .:/app
    restart: unless-stopped
    ports:
      - ${HOST_PORT:-8080}:${SERVER_PORT:-8080}
